apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  labels:
    app: nginx

spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: brunomestanza/nlw.service.passin:3a679d3
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: url
            - name: API_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: nlw-env
                  key: url
          ports:
            - containerPort: 3333
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi