apiVersion: v1
kind: Service

metadata:
  name: ngix-service
  labels:
    app: ngix

spec:
  selector:
    app: ngix
  type: ClusterIP
  ports:
    - name: ngix-service
      port: 80
      targetPort: 80
      protocol: TCP